---
# defaults file for workers
kube_proxy_url: https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kube-proxy
kubelet_url: https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kubelet
crictl_url: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.18.0/crictl-v1.18.0-linux-amd64.tar.gz
runc_url: https://github.com/opencontainers/runc/releases/download/v1.0.0-rc91/runc.amd64
cni_plugins_linux_url: https://github.com/containernetworking/plugins/releases/download/v0.8.6/cni-plugins-linux-amd64-v0.8.6.tgz
containerd_url: https://github.com/containerd/containerd/releases/download/v1.3.6/containerd-1.3.6-linux-amd64.tar.gz


cluster_cidr: 10.200.0.0/16
cluster_dns: "10.32.0.10" ## This IP is based on Service IP range. The default value is 10.32.0.0/24